name: Build Windows EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install PyInstaller
        run: pip install pyinstaller
      - name: Install PyQt6
        run: pip install PyQt6
      - name: Build EXE
        run: pyinstaller main.py --onefile
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: yourapp
          path: dist/
          
